## Python Library Name: NumPy - NUMerical PYthon
---
***used for scientific computing and data analysis***

***uses n-dimensional, homogenous objects (`ndarray`)***

***Provide tools for integrating C, C++ etc.***

Power of NumPy is N-dimensional object which is in the form of `rows` and `columns`

**Why NumPy? Why can't list/tuple/ set. etc**
- Fast
- Less Memory
- Convenient
- Vectorized code (Code does not contain explicit looping and indexing..etc)
---


## NumPy Fundamentals
---

In [2]:
# import the NumPy module
import numpy as np

# Creating 1D array
fromList_to_1dArray = np.array([10,20,30,40,50])
fromTuple_to_1dArray = np.array((10,20,30))

print(fromList_to_1dArray)
print(type(fromList_to_1dArray))

print(fromTuple_to_1dArray)
print(type(fromTuple_to_1dArray))

[10 20 30 40 50]
<class 'numpy.ndarray'>
[10 20 30]
<class 'numpy.ndarray'>


In [6]:
# Creating 2D array
fromList_to_2dArray = np.array([[10,20,30,40,50], [60,70,80,90,100]])
fromList_to_2dArray

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [7]:
num_array1 = np.array([1,2,3,4,5])
num_array2 = np.array([10,20,30,40,50])
summa = num_array1 + num_array2
print(summa)
print(type(summa))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [50]:
# lets convert summa to float array
summa_float = np.array(summa,dtype=float)
summa_float


array([11., 22., 33., 44., 55.])

In [55]:
# Lets slicing the actual elements
print(summa_float[0:3])
print(summa_float[0:3][0])

[11. 22. 33.]
11.0


---

## How to initialize np arrays when size is known
----
***Functions that are used to do so are:***
- `np.arange()`: Array creation with defined increments.
- `np.zeros()`: Array of 0s.
- `np.ones()`: Array of 1s.
- `np.random.random()`: Array of random numbers
- `np.random.randint()`: Random array of integers within a particular range.
- `np.linespace()`: Array of fixed length.
- `np.full()`: Constant array of any number `n`.
- `np.eye()`: Identity matrix array (Pivot)
- `np.tile()`: Array is going to be created many times.


In [38]:
# Let's try some of these functions
step_by_2 = np.arange(1,15, 2)
step_by_2

array([ 1,  3,  5,  7,  9, 11, 13])

In [45]:
# zeros_func = np.zeros(5)
zeros_func = np.zeros((5,5))
zeros_func


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
import pandas as pd
import numpy as np

rand = np.random.random((5,5))   #float random numbers
data = pd.DataFrame(rand)
# lets sort it
data.sort_values(by=0, ascending=True)

0         1         2         3         4
4  0.140656  0.196823  0.715649  0.561048  0.458284
0  0.444758  0.141714  0.127848  0.180880  0.501842
2  0.455667  0.730533  0.592672  0.495963  0.997068
3  0.482258  0.542189  0.128351  0.001483  0.385764
1  0.677926  0.533984  0.945581  0.646368  0.463329

In [6]:
randint = np.random.randint(low=1, high=10, size=(10,5), dtype=int)   #integers numbers
pd.DataFrame(randint)

0  1  2  3  4
0  6  4  6  9  6
1  9  5  1  5  6
2  2  6  3  8  2
3  8  3  4  1  2
4  7  1  9  1  5
5  9  7  2  4  5
6  5  1  8  7  1
7  2  8  4  4  5
8  5  9  9  3  7
9  5  5  6  3  6

In [32]:
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [35]:
# Creating a Pivot matrix
matrix = np.eye(5, dtype=int)    #5x5
matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [41]:
# For creating a fix length
np.linspace(0,2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
# for repeating the same list of values
array = [1,2,3]
np.tile(array, (4, 5))    # repeating 5 times in 4 columns

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

---

## Structure of Array

**How to find out details of the arrays:**

- `size`: Check the size of the array.
- `dtype`: finds the type of the arrays.
- `shape`: shows shape of array (n x m).
- `itemsize`: Memory used by each array element in bytes.
- `ndim`: Number of axes (or dimensions)


In [8]:
array = np.random.randint(1, 10 , (5,3))
array

array([[3, 6, 7],
       [5, 3, 3],
       [3, 4, 9],
       [3, 5, 3],
       [9, 4, 1]])

In [11]:
print(array.size)
print(array.dtype)
print(array.shape)
print(array.itemsize)
print(array.ndim)

15
int32
(5, 3)
4
2


In [27]:
array_3d = np.arange(12)
print(array_3d, '\n-------------\n')

# for reshaping it, we can use `reshape(#No. elements in sub-sub-list, #No. lists in sub-list, #No. of lists)` 
print(array_3d.reshape(4,3), '\n-------------\n')
print(array_3d.reshape(2,3,2))


[ 0  1  2  3  4  5  6  7  8  9 10 11] 
-------------

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
-------------

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [32]:
#We can also `resizing` the array
matrix = np.resize(array_3d, (4,3)) 
matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
# Transpose of a matrix
matrix.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [37]:
#deleting element of matirx
np.delete(matrix, matrix[0][0])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

---

## Split / Join / Stack Array
---
- `np.r_[]` : Arange array **row-wise**.
- `np.c_[]`: Arange arrays **column-wise**.
- `np.concatenate()` : Concatenate two arrays.
- `np.hstack()`: Stack arrays **horizontally**.
- `np.vstack()`: Stack arrays **Vertically**.

In [4]:
array1 = np.random.randint(0, 10, (5,5))
array2 = np.random.randint(0, 10, (5,5))
print(array1)
print()
print(array2)

[[7 6 0 6 2]
 [7 5 4 2 6]
 [8 7 7 7 1]
 [4 9 4 9 4]
 [4 6 5 4 3]]

[[9 1 0 8 6]
 [5 7 5 8 2]
 [3 2 3 2 8]
 [4 5 5 3 1]
 [7 5 1 7 9]]


In [5]:
np.r_[(array1, array2)]

array([[7, 6, 0, 6, 2],
       [7, 5, 4, 2, 6],
       [8, 7, 7, 7, 1],
       [4, 9, 4, 9, 4],
       [4, 6, 5, 4, 3],
       [9, 1, 0, 8, 6],
       [5, 7, 5, 8, 2],
       [3, 2, 3, 2, 8],
       [4, 5, 5, 3, 1],
       [7, 5, 1, 7, 9]])

In [6]:
np.c_[(array1, array2)]


array([[7, 6, 0, 6, 2, 9, 1, 0, 8, 6],
       [7, 5, 4, 2, 6, 5, 7, 5, 8, 2],
       [8, 7, 7, 7, 1, 3, 2, 3, 2, 8],
       [4, 9, 4, 9, 4, 4, 5, 5, 3, 1],
       [4, 6, 5, 4, 3, 7, 5, 1, 7, 9]])

In [17]:
np.concatenate([array1, array2])

array([[7, 6, 0, 6, 2],
       [7, 5, 4, 2, 6],
       [8, 7, 7, 7, 1],
       [4, 9, 4, 9, 4],
       [4, 6, 5, 4, 3],
       [9, 1, 0, 8, 6],
       [5, 7, 5, 8, 2],
       [3, 2, 3, 2, 8],
       [4, 5, 5, 3, 1],
       [7, 5, 1, 7, 9]])

In [18]:
np.hstack([array1, array2])

array([[7, 6, 0, 6, 2, 9, 1, 0, 8, 6],
       [7, 5, 4, 2, 6, 5, 7, 5, 8, 2],
       [8, 7, 7, 7, 1, 3, 2, 3, 2, 8],
       [4, 9, 4, 9, 4, 4, 5, 5, 3, 1],
       [4, 6, 5, 4, 3, 7, 5, 1, 7, 9]])

In [19]:
np.vstack([array1, array2])

array([[7, 6, 0, 6, 2],
       [7, 5, 4, 2, 6],
       [8, 7, 7, 7, 1],
       [4, 9, 4, 9, 4],
       [4, 6, 5, 4, 3],
       [9, 1, 0, 8, 6],
       [5, 7, 5, 8, 2],
       [3, 2, 3, 2, 8],
       [4, 5, 5, 3, 1],
       [7, 5, 1, 7, 9]])